### PR TITLE
Translate values for campaigns

### PR DESCRIPTION
**Pull request by tsujigiri**

### CODE REVIEW

**Comment by RKushnir** [comment]
WDYT about using names without `_id` postfix for named values?
`account_status: :pending` <-> `account_status_id: 3`
This reads more intuitive, but on the other side allows for ambiguity when both attributes are passed.

**Comment by tsujigiri** [comment]
I like the idea, since then we don't need to inspect the value at all and can always assume that with `_id` suffix it's numeric and without it's human readable.

**Comment by dziemba** [comment]
> can always assume that with `_id` suffix it's numeric

We already fell into that trap. For example `tax_id` is *not* numeric, but rather something like `DE123123`. There are a few others. Not sure if this applies here, just wanted to warn you 😉

**Comment by tsujigiri** [comment]
What I mean ist that keys, that are present in `Const::CONSTS`, but are passed without the `_id` suffix, need translating. The others can be ignored.

**Comment by tsujigiri** [comment]
There are some that still cannot be ignored, since they don't have an `_id` suffix, but still... WDYT?

**Comment by dziemba** [comment]
🍄

**Pull request merged**
